# Generated by Django 5.0 on 2023-12-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_type_categories_typi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=128)),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='app.categories')),
            ],
        ),
    ]
